language: node_js # Node.js based project
node_js:
  - 12 # Level of Node.js to use
cache:
  directories:
    - website/node_modules # Cache the node_modules folder for quicker build times
script:
  - npm run build # Runs next build
  - npm run export # Runs next export and generates the out directory
  - touch out/.nojekyll # Creates a file telling Github not to build the project using Jekyll
deploy:
  provider: pages # Informs Travis this is a deployment to GitHub Pages
  skip_cleanup: true # Prevents Travis from resetting the working directory made during the build
  github_token: 6f155d8bcac62116bad352e6aeb1acd50d48b0ab # GitHub access token to use when pushing to the gh-pages branch
  # local_dir: out # Directory to push to the gh-pages branch
  local_dir: website/out
  on:
    # Only deploy when the build is on master or main branch - two common default branch names
    # If you're using a different branch name, add it here
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|main)$
