[book]
authors = ["Miaad Teams"]
language = "en"
multilingual = false
src = "src"
title = "Lesan"

[output.html]
git-repository-url = "https://github.com/MiaadTeam/lesan"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/MiaadTeam/lesan/tree/main/pages/{path}"
additional-css = ["./css/animation-bench.css"]
default-theme = "Ayu"
